{% set version = "1.17.0" %}

package:
  name: wrapt
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/wrapt/wrapt-{{ version }}.tar.gz
  sha256: 16187aa2317c731170a88ef35e8937ae0f533c402872c1ee5e6d079fcf320801

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools >=38.3.0
    - wheel
  run:
    - python

test:
  imports:
    - wrapt
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/GrahamDumpleton/wrapt
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Module for decorators, wrappers and monkey patching
  description: |
    The aim of the wrapt module is to provide a transparent object proxy for
    Python, which can be used as the basis for the construction of function
    wrappers and decorator functions.
  doc_url: https://wrapt.readthedocs.io
  dev_url: https://github.com/GrahamDumpleton/wrapt

extra:
  recipe-maintainers:
    - jakirkham
    - nehaljwani
    - ocefpaf
