{% set version = "1.14.0" %}

package:
  name: wrapt
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/wrapt/wrapt-{{ version }}.tar.gz
  sha256: 8323a43bd9c91f62bb7d4be74cc9ff10090e7ef820e27bfe8815c57e68261311

build:
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools >=38.3.0
    - wheel
  run:
    - python

test:
  imports:
    - wrapt
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/GrahamDumpleton/wrapt
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Module for decorators, wrappers and monkey patching
  description: |
    The aim of the wrapt module is to provide a transparent object proxy for
    Python, which can be used as the basis for the construction of function
    wrappers and decorator functions.
  doc_url: http://wrapt.readthedocs.org/en/latest/
  doc_source_url: https://github.com/GrahamDumpleton/wrapt/blob/master/docs/index.rst
  dev_url: https://github.com/GrahamDumpleton/wrapt

extra:
  recipe-maintainers:
    - jakirkham
    - nehaljwani
    - ocefpaf
