{% set version = "1.11.0" %}

package:
  name: wrapt
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/wrapt/wrapt-{{ version }}.tar.gz
  sha256: e03f19f64d81d0a3099518ca26b04550026f131eced2e76ced7b85c6b8d32128

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - wrapt

about:
  home: https://github.com/GrahamDumpleton/wrapt
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'Module for decorators, wrappers and monkey patching'
  description: |
    The aim of the wrapt module is to provide a transparent object proxy for
    Python, which can be used as the basis for the construction of function
    wrappers and decorator functions.
  doc_url: http://wrapt.readthedocs.org/en/latest/
  doc_source_url: https://github.com/GrahamDumpleton/wrapt/blob/master/docs/index.rst
  dev_url: https://github.com/GrahamDumpleton/wrapt

extra:
  recipe-maintainers:
    - jakirkham
    - nehaljwani
    - ocefpaf
