{% set name = "wrapt" %}
{% set version = "2.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9c9c635e78497cacb81e84f8b11b23e0aacac7a136e73b8e5b2109a1d9fc468f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<38]

requirements:
  build:
    #- {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - wheel
    - setuptools >=38.3.0
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - wrapt
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/GrahamDumpleton/wrapt
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Module for decorators, wrappers and monkey patching
  description: |
    The aim of the wrapt module is to provide a transparent object proxy for
    Python, which can be used as the basis for the construction of function
    wrappers and decorator functions.
  doc_url: https://wrapt.readthedocs.io
  dev_url: https://github.com/GrahamDumpleton/wrapt

extra:
  recipe-maintainers:
    - jakirkham
    - nehaljwani
    - ocefpaf
