travis:
  secure:
    BINSTAR_TOKEN: fpWbs2ryaMhwkplgApXde0DI3wskn3cdk99WSKCf1LTSlRUV44ZILf9ERWgumH8At92VnX+tLRroz5ajoootrilDQkHTolEhDJTBhUUVU9qw07VK+pZD4vUJ1GHO+hNtS5qA85pKkHuVRIhaQxFKLbGzwjMJOfAge8Q7qwBXC6SKuTgZsJW0qT9u4ASHJg9pLLK9CoZ8MF3n1N6zs0ZHSc0KtGvvmmahDCSFrwUxpq7uT0WqwdJ8abVFxazUHBK7PZ0JZNjhGFiYaJeelw1m+TKLKC95ZviXWKnrEXmH++tfe6ZZXPz0zGfg6eEx/ze1g5Cx2XST0R43/DhF2Jw56iUKb+iRa+XY6HWWn1nKalBKazojG/OKVbon/jWBpY0JE6/F+kD8VF4htGLjfTyuiurFCBaDN0NGkL/lZTvQHhn/7X5KB83lxcvI1nUJJu+EwTf+3AqhZ4uEYK0ZmTILp3T3WXzljySzZG6MuwyVIwGBkkY1G0Yo3RmfZzKLnV3dpyKBA85L6gyTNL5Jenl+0yqQWPxgoWG55+YhdqNeQJ8mEBe2L6EPZkhdke1jNJmFl9/qnoLe0YsYfSGPfaBlMGb64quPEBv8nnOJyHK2c07ijZDqVxAGqb/xf5k4xWslqTahI2oBNDDoVlXQoOJNmsz3TS4YqJFTC3jPJT6DyEI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
