travis:
  secure:
    BINSTAR_TOKEN: kmyzA3XNKwovrZpnSvy/pYA+KGhZU1r89fYd2EjpfuRxpWP87bVTEQnxhnaINWmtuIBb2cbn8wRHy03Xx0YzHQSgvn7t1eRbxNvrc+9WvmMe1Dq2+u2RnDZAOUzaCImX8Kplr8kW54FktTXutahQq3nYQMCO9zf1bGcvIA5kTrjE921QDuAbceBQ8GFts6Bi5GKf3+lQg1lcOnJ0IGsMpXztMXQ4NcHm0oXSm8giYRKHUq+kDdvCXKzzbKMnUQDL/hrTb1roh6XqGwS+TkGytwjRb7H4PhmxYpb4J0/l78INDvn7h0/TmbfikcEXaiq1cjALGypMzNy7HrIPFK6KQ0NNmwSkCEKsmD4lPPkY9nZcs2uG+FpEeIAwz7JElTjriUxN05ky0pQdfUXHkaGR/u/Wz81iSn1oGJvu1sEfqp1TMF2lDpZONKAvsd7yTvchMowa8PfbhuttKqU8tsd1oJ/lOB8OmRui3yprfEGiD9hbA8ZvxnaVm1qTn5g4cbmHSWsh7cQd4dEh1/e56o3zOAOnfGvt6w9i4z4MKgNLteGX5rteHyEa8ZOEgJMx9DeI8vjEcNyowVcoDK+Jv6ZoL7iizzDpKHocZD2t4nFPj0GyRjAzJi6PB/OX36OzBDZs9y5U6C1KsP4qS4QkS/37yg+RbJbwBHIA6TxT+QDIJlU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
